apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: generic-pr-
  name: generic-pipeline-run
spec:
  pipelineRef:
    name: build-pipeline
  resources:
    - name: git-source
      resourceRef:
        name: git-source
  params:
    - name: imageUrl
      value: addozhang/tekton-test
    - name: imageTag
      value: latest
  serviceAccountName: tekton-test
