apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: generic-pr-
  name: generic-pipeline-run
spec:
  pipelineRef:
    name: build-pipeline
  resources:
    - name: git-source
      resourceSpec:
        type: git
        params: 
          - name: revision
            value: master
          - name: url
            value: https://github.com/addozhang/tekton-test.git
  params:
    - name: imageUrl
      value: addozhang/tekton-test
    - name: imageTag
      value: latest
  serviceAccountName: tekton-test
