version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.nip.io'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
       external_url 'http://gitlab.nip.io:8088'
        gitlab_rails['gitlab_shell_ssh_port'] = 8022
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '8088:8088'
      - '8022:22'
    volumes:
      - '/tmp/gitlab/config:/etc/gitlab:cached'
      - '/tmp/gitlab/logs:/var/log/gitlab:cached'
      # - '/tmp/gitlab/data:/var/opt/gitlab' #disable due to directory permission issue