apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: tekton-test-
spec:
  params:
    - name: PULL_BASE_REF
      value: 
    - name: REPO_URL
      value: 
    - name: imageUrl
      value: addozhang/tekton-test
    - name: imageTag
      value: latest
  pipelineSpec:
    params:
      - name: REPO_URL
      - name: PULL_BASE_REF
      - name: pathToContext
        description: The path to the build context, used by Kaniko - within the workspace
        default: .
      - name: imageUrl
        description: Url of image repository
      - name: imageTag
        description: Tag to apply to the built image  
    workspaces:
      - name: git-source
      - name: docker-config        
    tasks:
      - name: fetch-from-git
        taskRef:
          name: git-clone
        params:
          - name: url
            value: "$(params.REPO_URL)"
          - name: revision
            value: "$(params.PULL_BASE_REF)"
        workspaces:
          - name: output
            workspace: git-source
      - name: source-to-image
        taskRef:
          name: source-to-image
        params:
          - name: imageUrl
            value: "$(params.imageUrl)"
          - name: imageTag
            value: "$(params.imageTag)"
        workspaces:
          - name: source
            workspace: git-source
          - name: dockerconfig
            workspace: docker-config
        runAfter:
          - fetch-from-git
      - name: deploy-to-k8s
        taskRef: 
          name: deploy-to-k8s
        params:
          - name: pathToYamlFile
            value: deployment.yaml
        workspaces:
          - name: source
            workspace: git-source
        runAfter:
          - source-to-image
  workspaces:
    - name: git-source
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: docker-config
      secret:
        secretName: docker-config
  serviceAccountName: tekton-build
